import MyDocusealBuilder from "@/components/my-docuseal/MyDocusealBuilder";
const token =
	"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2VtYWlsIjoiYmlsbGluZ0BzYWFzdGFpbi5hcHAiLCJpbnRlZ3JhdGlvbl9lbWFpbCI6InNlYW52aW5jZW50OTk2QGdtYWlsLmNvbSIsImV4dGVybmFsSWQiOiJaRjluTFVyQlRUeVk4cmxCWXhKSzYiLCJuYW1lIjoiU0xBLVZlbmRvci1TTUUiLCJkb2N1bWVudFVybHMiOlsiaHR0cHM6Ly9maXJlYmFzZXN0b3JhZ2UuZ29vZ2xlYXBpcy5jb20vdjAvYi9zYWFzdGFpbi1kb2NzLmFwcHNwb3QuY29tL28vbG9hbi1hcHBsaWNhdGlvbiUyRmRvY3VtZW50cyUyRjQ1NzM5NTRjLWE3YjctNDU2OS05MTdhLWRjNmE0MWU3NGY4MiUyRkphbWJvamV0LmNvbSUyMC0lMjBJdGluZXJhcnlfcjRYZlI0Xy5wZGY_YWx0PW1lZGlhJnRva2VuPTBkOTE4MDA3LTYxMzgtNDMzNi1iZDAyLTBmNzlmNmIzNjNjZCJdLCJpYXQiOjE3MjUxNzkwNTl9.uTmoXi-k97G0mYn9ogqPz5oT4kNWSWnfBkPg9H4tpVQ";

const page = () => {
	return <MyDocusealBuilder token={token} />;
};

export default page;
